![title](images/01title.jpeg)

這裡我們介紹 `numpy array` 的基礎, 尤其和線性代數有關的。

我們使用的課本是 [Mathematics for Machine Learning](https://mml-book.github.io), 所以很多例子是從課本來的。

### 0. 基本套件讀入

In [1]:
%matplotlib inline

import numpy as np
import matplotlib.pyplot

### 1. `numpy array` 純量乘法

因為 `array` brocasting (廣播) 特性, 我們很容易可以做純量乘法。

In [2]:
x = np.array([1, 2, 3])

In [3]:
x

array([1, 2, 3])

In [4]:
3*x

array([3, 6, 9])

#### 矩陣表示法

矩陣是一列一列 (一個 row 一個 row) 的表示。比如說, 我們想定義一個矩陣:

$$A = \begin{bmatrix}1 & 2 & 3\\ 4 & 5 & 6\end{bmatrix}$$

注意: 中國大陸和台灣「列」和「行」用法是相反的。

In [5]:
A = np.array([[1, 2, 3],
             [4, 5, 6]])

In [6]:
A

array([[1, 2, 3],
       [4, 5, 6]])

#### 注意

其實 `numpy` 有「真的」矩陣資料型態, 不過因為 `array` 是 `numpy` 比較自然的型態, 所以我們基本上都會直接使用 `array` 來計算。

剛剛的 A 矩陣當然也可以做純量乘法。

In [7]:
3*A

array([[ 3,  6,  9],
       [12, 15, 18]])

### 2. 向量加法

在 `array` 裡顯得很自然。

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [9]:
x + y

array([5, 7, 9])

### 3. 內積是矩陣乘法的核心

我們有兩個矩陣 $A \in \mathbb{R}^{m\times k}$, $B \in \mathbb{R}^{k \times n}$, 如果

$$C = AB,$$

那我們知道 $C \in \mathbb{R}^{m \times n}$, 並且裡面的元素

$$c_{ij} = A_{(i)} B^{(j)},$$

其中 $A_{(i)}$ 表 $A$ 的第 $i$ 列; $B^{(j)}$ 表 $B$ 的第 $j$ 行。寫出來會是:

$$c_{ij} = [a_{i1} a_{i2} \ldots a_{ik}] \cdot \begin{bmatrix}
b_{1j}\\ b_{2j} \\ \vdots \\ b_{kj}\end{bmatrix}
= \sum_{\ell = 1}^k a_{i\ell} b_{\ell j}.$$

仔細看看其實不過就是做 $A_{(i)}$, $B^{(j)}$ 這兩個向量的標準內積 (dot product)。所以矩陣乘法就是做很多的內積!

內積在 `numpy` 指令是 `np.dot`, 不過因為太常用了, 較新的版本就使用了 `@`。

In [10]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 6])

In [11]:
np.dot(x, y)

26

In [12]:
x@y

26

前面說到, 矩陣乘法只是一直一直做內積, 所以矩陣的乘法就是用 `@`。

In [13]:
A = np.array([[1,2,3],[3,2,1]])
B = np.array([[0,2], [1,-1], [0,1]])

In [14]:
A@B

array([[2, 3],
       [2, 5]])

In [15]:
B@A

array([[ 6,  4,  2],
       [-2,  0,  2],
       [ 3,  2,  1]])

順便我們也發現 $AB \neq BA$。

### 4. Identity Matrix $I_n$

我們可以快速的造出 $n \times n$ identity matrix。

In [16]:
I3 = np.eye(3)

In [17]:
I3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 5. 反矩陣

In [18]:
A = np.array([[1,2,1],[4,4,5],[6,6,7]])

In [19]:
A

array([[1, 2, 1],
       [4, 4, 5],
       [6, 6, 7]])

再一次, 因為我們堅持要用 `array` 來做矩陣運算, 所以有時候指令會看來複雜一點。

In [20]:
B = np.linalg.inv(A)

這裡 `np.linalg` 當然是 `numpy` 裡的 Linear Algebra 子套件, 之後的 `inv` 就是求 inverse, 這還可接受,  只是看到內容我們就驚呆了!

In [21]:
B

array([[-1.00000000e+00, -4.00000000e+00,  3.00000000e+00],
       [ 1.00000000e+00,  5.00000000e-01, -5.00000000e-01],
       [-6.66133815e-16,  3.00000000e+00, -2.00000000e+00]])

這是... 會不會是因為這個反矩陣比較複雜, 我們把 A 和 B 乘一乘, 應該會得到單位矩陣。

In [22]:
C = A@B

In [23]:
C

array([[ 1.00000000e+00, -4.44089210e-16, -2.22044605e-16],
       [-2.22044605e-16,  1.00000000e+00, -6.66133815e-16],
       [-2.22044605e-16, -8.88178420e-16,  1.00000000e+00]])

用力看好像是單位矩陣, 可是我們能確認嗎? 可以用 `np.allclose` 試試。

In [24]:
np.allclose(C, np.eye(3))

True

真的是耶, 但難道不能美化一點...

### 6. `round`

`round` 「基本上」很「接近」四捨五入, 但是...

In [25]:
u = np.array([-1.5, -0.5, 0.5, 1.5, 2.5])

In [26]:
u.round()

array([-2., -0.,  0.,  2.,  2.])

看出發生什麼事了嗎? 原來 `round` 真的是會往「比較接近」的整數去。但是, 正好在兩個整數中間 (x.5) 怎麼辦呢? 它會讓數字往比較接近的那個「偶數」去!

還有一個問題, 那個 $-0$ 是什麼? 哦, 原來是從小於 $0$ 的方向過來的數字, 要變「正常」有個小技巧, 都加上 $0$ 就好!

In [27]:
u.round() + 0

array([-2.,  0.,  0.,  2.,  2.])

好, 我們現在回來看可怕的矩陣 $B$ 和 $C$。我們先看一下 $B$。

In [28]:
B

array([[-1.00000000e+00, -4.00000000e+00,  3.00000000e+00],
       [ 1.00000000e+00,  5.00000000e-01, -5.00000000e-01],
       [-6.66133815e-16,  3.00000000e+00, -2.00000000e+00]])

In [29]:
B.round()

array([[-1., -4.,  3.],
       [ 1.,  0., -0.],
       [-0.,  3., -2.]])

哦! 這順眼多了! 可是還是有 $-0$。不緊張, 我們就加上 $0$。

In [30]:
B.round() + 0

array([[-1., -4.,  3.],
       [ 1.,  0.,  0.],
       [ 0.,  3., -2.]])

再看一下應該是單位矩陣的 $C$, 有經驗了我們直接加 $0$。

In [31]:
C.round() + 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])